In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("mymoviedb.csv",lineterminator='\n')

In [4]:
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9827 entries, 0 to 9826
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9827 non-null   object
 1   Title              9827 non-null   object
 2   Overview           9827 non-null   object
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   int64
 5   Vote_Average       9827 non-null   float64
 6   Original_Language  9827 non-null   object
 7   Genre              9827 non-null   object
 8   Poster_Url         9827 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 691.1+ KB

In [6]:
df.isnull().sum()

Release_Date         0
Title                0
Overview             0
Popularity           0
Vote_Count           0
Vote_Average         0
Original_Language    0
Genre                0
Poster_Url           0
dtype: int64

In [7]:
df['Genre'].head()

0    Action, Adventure, Science Fiction
1              Crime, Mystery, Thriller
2                              Thriller
3    Animation, Comedy, Family, Fantasy
4      Action, Adventure, Thriller, War
Name: Genre, dtype: object

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

        Popularity    Vote_Count  Vote_Average
count  9827.000000   9827.000000   9827.000000
mean     40.326088   1392.805536      6.439534
std     108.873998   2611.206907      1.129759
min      13.354000      0.000000      0.000000
25%      16.128500    146.000000      5.900000
50%      21.199000    444.000000      6.500000
75%      35.191500   1376.000000      7.100000
max    5083.954000  31077.000000     10.000000

In [13]:
df['Release_Date']= pd.to_datetime(df['Release_Date'])

print(df['Release_Date'].dtypes)

datetime64[ns]

In [14]:
df['Release_Year']=df['Release_Date'].dt.year

In [15]:
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url,Release_Year
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...,2021
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...,2022
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...,2022
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...,2021
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...,2021

In [16]:
#Dropping the columns
cols=['Release_Date','Overview','Original_Language','Poster_Url']

clean_df=df.drop(cols,axis=1)

In [17]:
clean_df.head()

,Title,Popularity,Vote_Count,Vote_Average,Genre,Release_Year
0,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction",2021
1,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller",2022
2,No Exit,2618.087,122,6.3,Thriller,2022
3,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy",2021
4,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War",2021

In [21]:
#categorizing the vote Averge column
def categorized_column(df,col,labels):
    edges = [df[col].min(),
            df[col].quantile(0.25),
            df[col].quantile(0.50),
            df[col].quantile(0.75), 
            df[col].max()]

    df['Vote_Category'] = pd.cut(df[col], bins=edges , labels= labels,duplicates='drop')
    return df

In [24]:
labels=['not_popular','below_average','average','popular']

categorized_column(clean_df,'Vote_Average',labels)

,Title,Popularity,Vote_Count,Vote_Average,Genre,Release_Year,Vote_Category
0,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction",2021,popular
1,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller",2022,popular
2,No Exit,2618.087,122,6.3,Thriller,2022,below_average
3,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy",2021,popular
4,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War",2021,average
...,...,...,...,...,...,...,...
9822,Badlands,13.357,896,7.6,"Drama, Crime",1973,popular
9823,Violent Delights,13.356,8,3.5,Horror,2020,not_popular
9824,The Offering,13.355,94,5.0,"Mystery, Thriller, Horror",2016,not_popular
9825,The United States vs. Billie Holiday,13.354,152,6.7,"Music, Drama, History",2021,average
9826,Threads,13.354,186,7.8,"War, Drama, Science Fiction",1984,popular

In [26]:
clean_df['Vote_Category'].unique()

['popular', 'below_average', 'average', 'not_popular', NaN]
Categories (4, object): ['not_popular' < 'below_average' < 'average' < 'popular']

In [28]:
clean_df['Vote_Category'].value_counts()

Vote_Category
not_popular      2467
popular          2450
average          2412
below_average    2398
Name: count, dtype: int64

In [29]:
clean_df.isnull().sum()

Title              0
Popularity         0
Vote_Count         0
Vote_Average       0
Genre              0
Release_Year       0
Vote_Category    100
dtype: int64

In [30]:
clean_df.dropna(inplace=True)

In [32]:
clean_df.isnull().sum()

Title            0
Popularity       0
Vote_Count       0
Vote_Average     0
Genre            0
Release_Year     0
Vote_Category    0
dtype: int64

In [33]:
clean_df.head()

,Title,Popularity,Vote_Count,Vote_Average,Genre,Release_Year,Vote_Category
0,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction",2021,popular
1,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller",2022,popular
2,No Exit,2618.087,122,6.3,Thriller,2022,below_average
3,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy",2021,popular
4,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War",2021,average

In [34]:
#spreating genre into list and then explide our dataframe to have only one genre per row for each movie
clean_df['Genre']=clean_df['Genre'].str.split(', ')
clean_df.head()

,Title,Popularity,Vote_Count,Vote_Average,Genre,Release_Year,Vote_Category
0,Spider-Man: No Way Home,5083.954,8940,8.3,"[Action, Adventure, Science Fiction]",2021,popular
1,The Batman,3827.658,1151,8.1,"[Crime, Mystery, Thriller]",2022,popular
2,No Exit,2618.087,122,6.3,[Thriller],2022,below_average
3,Encanto,2402.201,5076,7.7,"[Animation, Comedy, Family, Fantasy]",2021,popular
4,The King's Man,1895.511,1793,7.0,"[Action, Adventure, Thriller, War]",2021,average

In [37]:
clean_df=clean_df.explode('Genre').reset_index(drop=True)
clean_df.head()

,Title,Popularity,Vote_Count,Vote_Average,Genre,Release_Year,Vote_Category
0,Spider-Man: No Way Home,5083.954,8940,8.3,Action,2021,popular
1,Spider-Man: No Way Home,5083.954,8940,8.3,Adventure,2021,popular
2,Spider-Man: No Way Home,5083.954,8940,8.3,Science Fiction,2021,popular
3,The Batman,3827.658,1151,8.1,Crime,2022,popular
4,The Batman,3827.658,1151,8.1,Mystery,2022,popular

In [40]:
#casting column into category 
clean_df['Genre']=clean_df['Genre'].astype('category')
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25552 entries, 0 to 25551
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Title          25552 non-null  object
 1   Popularity     25552 non-null  float64
 2   Vote_Count     25552 non-null  int64
 3   Vote_Average   25552 non-null  float64
 4   Genre          25552 non-null  category
 5   Release_Year   25552 non-null  int32
 6   Vote_Category  25552 non-null  category
dtypes: category(2), float64(2), int32(1), int64(1), object(1)
memory usage: 949.2+ KB

In [42]:
clean_df.nunique()

Title            9415
Popularity       8088
Vote_Count       3265
Vote_Average       73
Genre              19
Release_Year      100
Vote_Category       4
dtype: int64

In [47]:
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "root"
host = "localhost"
port = "3306"
database = "Netflix_movie_data"

engine = create_engine(f"mysql+pymysql://{"root"}:{"root"}@{"localhost"}:{3306}/{"Netflix_movie_data"}")

# Write DataFrame to MySQL
table_name = "movies_db"   # choose any table name
clean_df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM movies_db LIMIT 5;", engine)

,Title,Popularity,Vote_Count,Vote_Average,Genre,Release_Year,Vote_Category
0,Spider-Man: No Way Home,5083.954,8940,8.3,Action,2021,popular
1,Spider-Man: No Way Home,5083.954,8940,8.3,Adventure,2021,popular
2,Spider-Man: No Way Home,5083.954,8940,8.3,Science Fiction,2021,popular
3,The Batman,3827.658,1151,8.1,Crime,2022,popular
4,The Batman,3827.658,1151,8.1,Mystery,2022,popular